# -*- coding: utf-8 -*-
"""Kaggele version 30

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rL46Ef_Pj0Vce3ITUZ5mBRrt-TINB24P
"""

# ============================================================
# SETUP
# ============================================================
import os
import subprocess
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed

import kagglehub
from google.colab import userdata

username = userdata.get('KAGGLE_USERNAME')
key = userdata.get('KAGGLE_KEY')

# %env KAGGLE_USERNAME=$username
# %env KAGGLE_KEY=$key

get_ipython().system('pip install -q yt-dlp')
get_ipython().system('python -m pip install -q -U --force-reinstall --no-deps https://github.com/mikf/gallery-dl/archive/master.tar.gz')

# %%capture
# !kaggle datasets download faizkautsar/data-dfk3-aitf
# !rm -rf "/content/data-dfk3-aitf.zip"
# !unzip data-dfk3-aitf.zip -d aitf
# %cd aitf


# ============================================================
# CONFIG
# ============================================================
VIDEO_EXT = (".mp4", ".mov", ".avi", ".mkv", ".webm")
BASE_AITF  = "/content/aitf/Ai-content-tiktok"
BASE_NETRAL = "/content/aitf/video-netral"
MAX_VIDEOS = 300
CONCURRENT_FRAGMENTS = 4   # parallel HLS fragments per video

CHANNELS = [
    {"name": "CNN",       "url": "https://www.tiktok.com/@cnnindonesia"},
    {"name": "detik",     "url": "https://www.tiktok.com/@detikcom"},
    {"name": "tempo",     "url": "https://www.tiktok.com/@tempo.co"},
    {"name": "liputan6",  "url": "https://www.tiktok.com/@liputan6com"},
    {"name": "antara",    "url": "https://www.tiktok.com/@antaranews"},
    # {"name": "kompas",    "url": "https://www.tiktok.com/@kompascom"},
    # {"name": "beritasatu","url": "https://www.tiktok.com/@beritasatuofficial"},
    # {"name": "kumparan",  "url": "https://www.tiktok.com/@kumparan"},
]


# ============================================================
# STEP 1 — CLEAN MP3 FILES (Ai-content-tiktok)
# ============================================================
deleted = 0
for root, _, files in os.walk(BASE_AITF):
    for f in files:
        if f.lower().endswith(".mp3"):
            os.remove(os.path.join(root, f))
            deleted += 1
print("MP3 deleted:", deleted)


# ============================================================
# SHARED HELPERS
# ============================================================
def build_file_map(videos_path):
    """Map video_id → filename for a /videos directory."""
    file_map = {}
    if not os.path.exists(videos_path):
        return file_map
    for f in os.listdir(videos_path):
        if not f.lower().endswith(VIDEO_EXT):
            continue
        name = os.path.splitext(f)[0]
        file_map[name] = f
        if "_" in name:
            file_map[name.split("_")[-1]] = f
    return file_map


def load_metadata(csv_path):
    """Load metadata CSV robustly; handles comma and tab separators."""
    for sep in ("\t", ",", None):
        try:
            kwargs = {"header": None, "engine": "python", "on_bad_lines": "skip"}
            if sep:
                kwargs["sep"] = sep
            df = pd.read_csv(csv_path, **kwargs)
            if len(df.columns) >= 4:
                break
        except Exception:
            continue

    ncols = len(df.columns)
    if ncols >= 5:
        df = df.iloc[:, :5]
        df.columns = ["video_id", "date", "url", "title", "caption_post"]
    else:
        df = df.iloc[:, :4]
        df.columns = ["video_id", "date", "url", "title"]
        df["caption_post"] = ""

    df["video_id"] = df["video_id"].astype(str).str.strip().str.replace('"', '')
    df["title"] = df["title"].astype(str).str.strip()
    df["caption_post"] = df["caption_post"].astype(str).str.strip()
    return df


def build_video_index(folder_path):
    """Map video_id fragments → full path for a channel folder."""
    index = {}
    videos_path = os.path.join(folder_path, "videos")
    if not os.path.exists(videos_path):
        return index
    for f in os.listdir(videos_path):
        if f.lower().endswith(VIDEO_EXT):
            full = os.path.join(videos_path, f)
            name = f.split(".")[0]
            index[name] = full
            for part in name.split("_"):
                index[part] = full
    return index


# ============================================================
# STEP 2 — BUILD METADATA (Ai-content-tiktok)
# ============================================================
all_data = []

for folder in os.listdir(BASE_AITF):
    folder_path = os.path.join(BASE_AITF, folder)
    if not os.path.isdir(folder_path):
        continue

    metadata_path = os.path.join(folder_path, "metadata.csv")
    videos_path   = os.path.join(folder_path, "videos")

    if not (os.path.exists(metadata_path) and os.path.exists(videos_path)):
        continue

    df = load_metadata(metadata_path)
    file_map = build_file_map(videos_path)
    df["filename"] = df["video_id"].map(file_map)
    df = df.dropna(subset=["filename"])
    df["path"]    = df["filename"].apply(lambda x: f"{folder}/videos/{x}")
    df["creator"] = folder
    all_data.append(df)

final_aitf = pd.concat(all_data, ignore_index=True)
final_aitf = final_aitf[final_aitf["filename"].str.lower().str.endswith(VIDEO_EXT)]

output_path = os.path.join(BASE_AITF, "global_metadata.csv")
final_aitf.to_csv(output_path, index=False)
print("FINAL DATASET (Ai-content-tiktok)")
print("Total rows:", len(final_aitf))
print("Saved:", output_path)

# Sanity check
total_videos = sum(
    1 for root, _, files in os.walk(BASE_AITF)
    for f in files if f.lower().endswith(VIDEO_EXT)
)
print("Video files on disk:", total_videos)
assert len(final_aitf) == total_videos, "Dataset mismatch!"


# ============================================================
# STEP 3 — VALIDATE VIDEOS (Ai-content-tiktok)
# ============================================================
import cv2

invalid = [
    p for p in final_aitf["path"]
    if not cv2.VideoCapture(os.path.join(BASE_AITF, p)).isOpened()
]
print("Corrupt videos:", len(invalid))


# ============================================================
# STEP 4 — DOWNLOAD NETRAL CHANNELS (parallel)
# ============================================================
# Tab-separated metadata: id \t date \t url \t title \t description(caption)
META_TEMPLATE = "%(id)s\t%(upload_date>%Y-%m-%d)s\t%(webpage_url)s\t%(title)s\t%(description)s"


def download_channel(ch: dict) -> tuple:
    """Download one TikTok channel. Runs in a thread."""
    name = ch["name"]
    url  = ch["url"]
    out_dir  = os.path.join(BASE_NETRAL, name, "videos")
    meta_csv = os.path.join(BASE_NETRAL, name, "metadata.csv")
    os.makedirs(out_dir, exist_ok=True)

    cmd = [
        "yt-dlp",
        "-o",  f"{out_dir}/%(upload_date>%Y-%m-%d)s_%(id)s.%(ext)s",
        "-f",  "best[ext=mp4]",
        "-I",  f"1:{MAX_VIDEOS}",
        "--concurrent-fragments", str(CONCURRENT_FRAGMENTS),
        "--print-to-file", META_TEMPLATE, meta_csv,
        url,
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    print(f"[{name}] exit={result.returncode}")
    if result.stderr:
        for line in result.stderr.splitlines()[-5:]:   # last 5 error lines
            print(f"  [{name}] {line}")
    return name, result.returncode


print(f"Downloading {len(CHANNELS)} channels in parallel...")
with ThreadPoolExecutor(max_workers=len(CHANNELS)) as pool:
    futures = {pool.submit(download_channel, ch): ch["name"] for ch in CHANNELS}
    results = {}
    for future in as_completed(futures):
        name, rc = future.result()
        results[name] = rc

print("Download results:", results)


# ============================================================
# STEP 5 — BUILD METADATA (video-netral)
# ============================================================
all_netral = []

for folder in os.listdir(BASE_NETRAL):
    folder_path = os.path.join(BASE_NETRAL, folder)
    if not os.path.isdir(folder_path):
        continue

    csv_path = os.path.join(folder_path, "metadata.csv")
    if not os.path.exists(csv_path):
        continue

    print(f"\nProcessing: {folder}")
    df = load_metadata(csv_path)
    video_index = build_video_index(folder_path)

    df["full_path"] = df["video_id"].map(video_index)
    df["exists"] = df["full_path"].notna()

    total   = len(df)
    matched = df["exists"].sum()
    print(f"  metadata: {total}  matched: {matched}  missing: {total - matched}")

    df = df[df["exists"]].copy()
    df["path"]    = df["full_path"].apply(lambda x: os.path.relpath(x, BASE_NETRAL))
    df["creator"] = folder
    all_netral.append(df)

if not all_netral:
    print("No data found")
else:
    final_netral = pd.concat(all_netral, ignore_index=True)
    out = os.path.join(BASE_NETRAL, "global_metadata_clean.csv")
    final_netral.to_csv(out, index=False)
    print(f"\nDONE — {len(final_netral)} rows saved to {out}")


# ============================================================
# STEP 6 — UPLOAD TO KAGGLE
# ============================================================
# %%writefile dataset-metadata.json
# {
#   "title": "Data DFK3 AITF",
#   "id": "faizkautsar/data-dfk3-aitf"
# }

get_ipython().system('pwd')
get_ipython().system('kaggle datasets version -p "." -m "add netral video" --dir-mode tar')
